x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.17-alpine
  working_dir: /most-popular
  restart: always
  volumes:
    - .:/most-popular:cached
    - ./node_modules:/most-popular/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

x-node-full: &node-full
  tty: true
  init: true
  image: node:14.17
  working_dir: /most-popular
  volumes:
    - ~/.gitconfig:/etc/gitconfig
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    - ~/.npmrc:/root/.npmrc
    - .:/most-popular:cached
    - ./node_modules:/most-popular/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  bash:
    <<: *node-full
    entrypoint: ["/bin/bash"]

  mongodb:
    tty: true
    image: mongo:5.0
    volumes:
      - mongodb:/data/db
    ports:
      - "37930:27017"

  redis:
    tty: true
    image: redis:6.0-alpine
    ports:
      - "37932:6379"

  api:
    <<: *node
    working_dir: /most-popular/api
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      REDIS_DSN: ${REDIS_DSN-redis://redis}
      MONGO_URL: ${MONGO_URL-mongodb://mongodb:27017}
    depends_on:
      - mongodb
      - redis
    ports:
      - "37934:37934"

volumes:
  yarn-cache: {}
  mongodb: {}
